title: <p align="center"> Artik Gupta </p>
logo: /assets/img/Profile_DP.jpeg
description:
  <p align="center">
  <a href="assets/Data_Science.pdf">Resume</a> |
  <a href="https://linkedin.com/in/artik-gupta">LinkedIn</a> |
  <a href="https://github.com/artik-gupta">GitHub</a>
  
  <br>   
  Data Scientist | Machine Learning Engineer | Agentic AI
  <br>
  </p>
